### ISSUE TITLE
change serializer from pickle to json

### ISSUE THREAD

**Issue by lestatcheb** [brightinteractive/django-encrypted-cookie-session#23]
https://docs.djangoproject.com/en/1.9/topics/http/sessions/#session-serialization

Django recommends to change from old pickle serializer to json because possible remote code execution vulnerability.

Can we switch this lib too?

Thank you.

**Comment by kumar303** [comment]
It sounds like a good idea. However, since the cookie is signed there is really no way to modify its contents (to exploit a pickle vulnerability).

**Comment by JordanBright** [comment]
As I understand it the concern with the signing is that because it's based on the `SECRET_KEY` any information leak of that key promotes easily to a remote code execution vulnerability because somebody could just modify their cookies to whatever they want and sign it with the same key.

I'll have to look into it a bit more but isn't that also a problem for this library if the `ENCRYPTED_COOKIE_KEYS` are leaked? An attacker could presumably modify their cookie to a validly signed-and-encrypted one that then executes when unpickling.

I may be being very stupid here so I'll have a bit more of a think about it. Regardless of if it is an issue I can't think of a good reason why we couldn't just wrap any other serializer with the encrpytion on top. Maybe a setting like `ENCRYPTED_COOKIE_SERIALIZER` that defaults to `PickleSerializer`, then change our serializer to use one of those instead of directly extending `PickleSerializer`.

I'll have more of a think.

**Comment by kumar303** [comment]
The cookie is first encrypted with a key from `ENCRYPTED_COOKIE_KEYS` and signed with the `SECRET_KEY`. This makes the attack you presented very difficult because the attacker needs two keys and they will also need to encrypt the malicious packet correctly. 

The attack is definitely possible if both keys were to leak out, yes. Keep in mind that if both keys leaked, all sorts of damage is possible. For example, people often use session data to flag whether the user has site-wide admin privileges so the attacker could turn themselves into a super user. 

I agree that remote code execution is probably the worst exploit in case of a leak though. It seems worth fixing but there are more protections in this library when compared to Django's session strategy so it's maybe not as urgent. That's why this library exists :)

**Comment by JordanBright** [comment]
> This makes the attack you presented very difficult because the attacker needs two keys and they will also need to encrypt the malicious packet correctly.
>
> The attack is definitely possible if both keys were to leak out, yes. Keep in mind that if both keys leaked, all sorts of damage is possible. 

Ok, that's my understanding too so it seems I havent been very stupid (yay). This library is better protected than the sign-only Django serializer but it still has the same 'problem' which is that an information leak of the keys (which is quite serious, as you mentioned) becomes a remote code execution (which is more serious). 

As far as we know there's no such information leak in Django or this library so there's no cause to panic right now, but a poorly coded application could easily be vulnerable.

I think the simplest solution is to make the change I mentioned above: wrap the serializer instead of extending it, and create an `ENCRYPTED_COOKIE_SERIALIZER` setting, set for compatibility to `django.contrib.sessions.serializers.PickleSerializer` by default (or the other pre-1.5 module). It's probably worth recommending that new users use the json serializer instead, if we do this.

Another option might be to tie the serializer to the key, so you could have something like

    ENCRYPTED_COOKIE_KEYS=[
        ('<json key>', 'django.contrib.sessions.serializers.JSONSerializer'),
        '<pickle key>', 
        '<pickle key>'
    ]

to provide a migration path for people using the pickle serializer who don't want to blow away all their sessions to make it this much more secure. I don't know if that would even work properly though so it's just a thought - presumably if your pickled data isn't also json-serializable then you'd have a pretty bad time.


For what it's worth, we're not likely to add either feature any time soon here but we're happy to review pull requests for it.

**Comment by steveherrin** [comment]
Can this be resolved now?
